### PR TITLE
self action module rewrite

### PR DESCRIPTION
**Pull request by PiZZAD0X**
- rewrote module
- adds small/large grass cutting options
- joke sip action

does not have a good animation for grass cutting... needs an appropriately timed action for grass cutting before merge

### CODE REVIEW

**Review by EM-Creations — APPROVED** [review]

**Comment by TheLocalPub** [comment]
We get this yet?

**Comment by joewhite94** [comment]
> We get this yet?

This has been in since 1.1.6 by the looks of it

**Comment by TheLocalPub** [comment]
Hmmmmm. Sure about that?

**Comment by joewhite94** [comment]
https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/281

**Comment by TheLocalPub** [comment]
Yeah seen.
But I've never had the option for several grass cutting sizes, unless I just literally haven't tried it since we added it....

**Comment by joewhite94** [comment]
Cut grass small/large is available, just tried it in eden. People just aren't top of updating the FW in their missions

**Pull request merged**
